### PR TITLE
Do not count a image race to the db as a problem

### PR DESCRIPTION
**Pull request by rogierslag**
As the name explains

### CODE REVIEW

**Comment by rogierslag** [comment]
I know its not pretty, but it reduces the verbosity in the logs significantly

**Comment by TiddoLangerak** [comment]
Yeah I know, and AFAIK there isn't any other way to do this either. Exception handling still sucks in JS.

**Comment by rogierslag** [comment]
Big dislike is that most libraries also refuse to add some kind of constant to the error, on which you can do matching to determine the seriousness of the error :\

**Comment by AlexKolpa** [comment]
To be fair this is not specific to JS per se. For magnet.me I had to do string checking in Java to determine which constraint was violated as well.

**Pull request merged**
